version: '3.9'

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    env_file: .env

volumes:
  postgres_data:
